# roles/grafana/tasks/configure.yml
---
- name: Ensure Grafana configuration directory exists
  ansible.builtin.file:
    path: /etc/grafana
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  tags: configure

# - name: Deploy Grafana configuration template
#   ansible.builtin.template:
#     src: grafana.ini.j2
#     dest: /etc/grafana/grafana.ini
#     owner: grafana
#     group: grafana
#     mode: '0644'
#   notify: Restart Grafana
#   tags: configure
