# roles/grafana/tasks/install.yml
---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
  tags: install

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: "{{ grafana_apt_key_url }}"
    state: present
  tags: repo

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "{{ grafana_apt_repo }}"
    state: present
    update_cache: true
  tags: repo

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: true
  tags: install
